theme: minima
title: Girls and coding
author: GitHub User
email: thfal.quinolina@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a girl learning how to code. My other intrest include photography and learning languages.

# social links
github_username:  quinthifal # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
