theme: minima
title: Girls and Coding
author: quinthifal
email: thifal.quinolina@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am learning how to code. My other intrest also includes, photography, reading, and learning languages.

# social links
github_username:  quinthifal # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
